apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: aws-ses-mock
  name: aws-ses-mock
  namespace: ecommerce
spec:
  containers:
  - image: dasprid/aws-ses-v2-local:2.3.1
    name: aws-ses-mock
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "128Mi"

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: aws-ses-mock
  name: aws-ses-mock
  namespace: ecommerce
spec:
  ports:
  - port: 8005
    protocol: TCP
    targetPort: 8005
  selector:
    run: aws-ses-mock
status:
  loadBalancer: {}
