# Read the current chart version and output it 3 variables
# -> 'chart_current_version.version' : the Chart version
# -> 'chart_current_version.appVersion': the application version
# -> 'chart_current_version.releaseUrl': the module release url formatted as https:://<<repo-url>>/releases/tag/v<<appVersion>>-RELEASE

steps:
  - task: Bash@3
    name: chart_current_version
    displayName: 'Read chart current version'
    inputs:
      targetType: "inline"
      script: |
        CHART_FILE="helm/Chart.yaml"
        version=$(yq -r '.version' $CHART_FILE)
        appVersion=$(yq -r '.appVersion' $CHART_FILE)
        trimmed_repo_url=$(echo $(Build.Repository.Uri) | sed -e "s/\.git//g")
        releaseUrl=$(echo $trimmed_repo_url/releases/tag/v$appVersion-RELEASE)
        echo "##vso[task.setvariable variable=version;isOutput=true]$version"
        echo "##vso[task.setvariable variable=appVersion;isOutput=true]$appVersion"
        echo "##vso[task.setvariable variable=releaseUrl;isOutput=true]$releaseUrl"
      failOnStderr: true
  