apiVersion: v2
name: pagopa-notifications-service
description: Microservice that handles notifications in ecommerce pagoPA
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: microservice-chart
  version: 1.17.0
  repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
