apiVersion: v2
name: pagopa-notifications-service
description: Microservice that handles notifications in pagoPA platform
type: application
version: 0.2.0
appVersion: 0.2.0
dependencies:
  - name: microservice-chart
    version: 2.3.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
