microservice-chart:
  namespace: "ecommerce"
  nameOverride: ""
  fullnameOverride: ""
  canaryDelivery:
    create: false
    ingress:
      bluegreen: false
      #set canary deployment with traffic balancing see https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#canary for more info
      header: true
      headerName: deployment
      headerValue: blue
      weightPercent: 10
      image:
        repository: pagopapcommonacr.azurecr.io/pagopanotificationsservice
        tag: "latest"
      envConfig:
        ELASTIC_APM_SERVICE_NAME: pagopa-notification-service-blue
      envSecret: {}
    deployment:
      image:
        tag: ""
  image:
    repository: pagopapcommonacr.azurecr.io/pagopanotificationsservice
    tag: "1.9.0"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /health/liveness
      port: 3000
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 60
  readinessProbe:
    httpGet:
      path: /health/readiness
      port: 3000
    initialDelaySeconds: 30
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 3
  service:
    create: true
    type: ClusterIP
    ports:
      - 3000
  ingress:
    create: true
    host: "weuprod.ecommerce.internal.platform.pagopa.it"
    path: /pagopa-notifications-service/(.*)
    servicePort: 3000
  serviceAccount:
    create: false
    annotations: {}
    name: "ecommerce-workload-identity"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "150m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 10
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  terminationGracePeriodSeconds: 30
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  envConfig:
    NOTIFICATIONS_EMAIL_ENABLED: "true"
    AWS_SES_REGION: "eu-south-1"
    CLIENT_ECOMMERCE_TEST: "{\"TEMPLATE_IDS\":[\"poc-1\", \"success\", \"ko\"]}"
    CLIENT_PAYMENT_MANAGER: "{\"TEMPLATE_IDS\":[\"poc-1\", \"success\", \"ko\"]}"
    CLIENT_ECOMMERCE: "{\"TEMPLATE_IDS\":[\"poc-1\", \"success\", \"ko\"]}"
    RETRY_QUEUE_NAME: "pagopa-p-weu-ecommerce-notifications-service-retry-queue"
    ERROR_QUEUE_NAME: "pagopa-p-weu-ecommerce-notifications-service-errors-queue"
    AI_SAMPLING_PERCENTAGE: "30"
    AI_ENABLED: "true"
    PAGOPA_MAIL_LOGO_URI: "https://checkout.pagopa.it/assets/logos/logo_pagopa.png"
    PERSONAL_DATA_VAULT_API_HOST: "https://api.tokenizer.pdv.pagopa.it"
    PERSONAL_DATA_VAULT_API_BASE_PATH: "/tokenizer/v1"
    ELASTIC_APM_SERVICE_NAME: pagopa-notification-service
    ELASTIC_APM_SERVER_URL: http://quickstart-apm-http.elastic-system.svc:8200
    ELASTIC_APM_ENVIRONMENT: "prod"
    SERVER_KEEP_ALIVE: "61000"
  envSecret:
    AWS_SES_ACCESS_KEY_ID: aws-ses-accesskey-id
    AWS_SES_SECRET_ACCESS_KEY: aws-ses-secretaccess-key
    STORAGE_TRANSIENT_CONNECTION_STRING: ecommerce-storage-transient-connection-string
    STORAGE_DEADLETTER_CONNECTION_STRING: ecommerce-storage-deadletter-connection-string
    PERSONAL_DATA_VAULT_API_KEY: personal-data-vault-api-key
    ECOMMERCE_NOTIFICATIONS_SENDER: notifications-sender
    ELASTIC_APM_SECRET_TOKEN: elastic-apm-secret-token
  keyvault:
    name: "pagopa-p-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: pagopanotificationsservice
            namespaces: ["ecommerce"]
            topologyKey: topology.kubernetes.io/zone
  azure:
    workloadIdentityClientId: "d5614882-90dd-47a1-aad1-cdf295201469"
