microservice-chart:
  namespace: "ecommerce"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: pagopadcommonacr.azurecr.io/pagopanotificationsservice
    tag: "0.1.10"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /health/liveness
      port: 3000
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 90
  readinessProbe:
    httpGet:
      path: /health/readiness
      port: 3000
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 3000
  ingress:
    create: true
    host: "weudev.ecommerce.internal.dev.platform.pagopa.it"
    path: /pagopa-notifications-service/(.*)
    servicePort: 3000
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  autoscaling:
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: azure-monitor
        metadata:
          tenantId: 7788edaf-0346-4068-9d79-c868aed15b3d
          subscriptionId: bbe47ad4-08b3-4925-94c5-1278e5819b86
          resourceGroupName: pagopa-d-ecommerce-sec-rg
          resourceURI: Microsoft.KeyVault/vaults/pagopa-d-ecommerce-kv
          metricName: ServiceApiHit
          # metricNamespace: Microsoft.KeyVault/vaults
          # metricFilter: namespace eq 'default'
          # metricAggregationInterval: "-1:1:0"
          metricAggregationType: Count
          targetValue: "30"
  envConfig:
    NOTIFICATIONS_EMAIL_ENABLED: "true"
    AWS_SES_REGION: "eu-south-1"
    CLIENT_ECOMMERCE_TEST: "{\"TEMPLATE_IDS\":[\"poc-1\", \"success\", \"ko\"]}"
    CLIENT_PAYMENT_MANAGER: "{\"TEMPLATE_IDS\":[\"poc-1\", \"success\", \"ko\"]}"
    CLIENT_ECOMMERCE: "{\"TEMPLATE_IDS\":[\"poc-1\", \"success\", \"ko\"]}"
    RETRY_QUEUE_NAME: "pagopa-d-weu-ecommerce-notifications-service-retry-queue"
    ERROR_QUEUE_NAME: "pagopa-d-weu-ecommerce-notifications-service-errors-queue"
    AI_SAMPLING_PERCENTAGE: "30"
    AI_ENABLED: "true"
    PAGOPA_MAIL_LOGO_URI: "https://dev.checkout.pagopa.it/assets/logos/pagopa-logo.svg"
  envSecret:
    AWS_SES_ACCESS_KEY_ID: aws-ses-accesskey-id
    AWS_SES_SECRET_ACCESS_KEY: aws-ses-secretaccess-key
    STORAGE_CONNECTION_STRING: ecommerce-storage-connection-string
    AI_INSTRUMENTATION_KEY: notifications-service-ai-instrumentation-key
  keyvault:
    name: "pagopa-d-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  canaryDelivery:
    deployment:
      image:
        tag: 0.1.10
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
